# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0006_auto_20160302_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 3, 3, 19, 47, 14, 785947)),
        ),
    ]
