# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0007_auto_20160303_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='accesibility',
            new_name='accessibility',
        ),
        migrations.AlterField(
            model_name='term',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 3, 12, 19, 4, 5, 251043)),
        ),
    ]
