# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terms', '0003_apitoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termhistory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='term',
            name='history',
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='accesibility',
            field=models.ManyToManyField(related_name='granted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terms.Author'),
        ),
        migrations.AddField(
            model_name='term',
            name='popularity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='term',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TermHistory',
        ),
    ]
